include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    todo: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true
    prefer_single_quotes: true
    avoid_catches_without_on_clauses: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true