name: lilafestivalapp
description: A festival app.

publish_to: 'none'

version: 2.0.4+8

environment:
  sdk: "^3.7.0"

dependencies:
  cached_network_image: ^3.4.1
  dime_flutter: ^0.6.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  hooks_riverpod: ^1.0.4
  http: ^1.3.0
  i18n_extension: ^15.0.5
  immortal: ^3.1.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  quiver: ^3.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  weather: ^3.2.1
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
     - assets/

  # TODO(SF) BUILD watch https://github.com/flutter/flutter/issues/21682
  fonts:
    - family: Display Font
      fonts:
        - asset: assets/display_font.ttf
    # - family: No Continue
    #   fonts:
    #     - asset: assets/spirit/no_continue.ttf
    # - family: Pirata One
    #   fonts:
    #     - asset: assets/party_san/PirataOne-Regular.ttf
