name: lilafestivalapp
description: A festival app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.10.0
  hooks_riverpod: ^0.3.0
  i18n_extension: ^1.4.1
  dime: ^0.4.0
  immortal: ^2.1.1
  url_launcher: ^5.4.11
  # flutter_launcher_icons: ^0.7.2+1
  # http: ^0.12.0+2
  # path_provider: ^1.2.0
  # optional: ^3.0.2+1
  # webview_flutter: ^0.3.10+4
  # flutter_local_notifications: ^0.8.0
  # dcache: ^0.3.0
  # cached_network_image: ^2.0.0
  # package_info: ^0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.3

flutter:
  uses-material-design: true

  # assets:
  #    - assets/initial_schedule.json
  #    - assets/bands.json
  #    - assets/logo.png
  #    - assets/icon_menu.png

  # fonts:
  #   - family: No Continue
  #     fonts:
  #       - asset: assets/no_continue.ttf

# flutter_icons:
#   image_path: "assets/icon.png"
#   android: true
#   adaptive_icon_background: "#000000"
#   adaptive_icon_foreground: "assets/icon_adaptive.png"
