name: lilafestivalapp
description: A festival app.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dime_flutter: ^0.6.0
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.4
  i18n_extension: ^5.0.0
  immortal: ^3.0.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  url_launcher: ^6.1.4
  weather: ^2.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.11
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
  uses-material-design: true

  assets:
     - assets/

  # TODO(SF) BUILD watch https://github.com/flutter/flutter/issues/21682
  fonts:
    - family: Display Font
      fonts:
        - asset: assets/display_font.ttf
    # - family: No Continue
    #   fonts:
    #     - asset: assets/spirit/no_continue.ttf
    # - family: Pirata One
    #   fonts:
    #     - asset: assets/party_san/PirataOne-Regular.ttf
