name: lilafestivalapp
description: A festival app.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.10.0
  hooks_riverpod: ^0.3.0
  i18n_extension: ^1.4.1
  dime: ^0.4.0
  immortal: ^2.1.1
  url_launcher: ^5.4.11
  package_info: ^0.4.1
  path_provider: ^1.6.11
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  weather: ^1.1.1
  dcache: ^0.3.0
  webview_flutter: ^0.3.22+1
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.3
  mockito: ^4.1.1
  # TODO(SF) BUILD watch https://github.com/fluttercommunity/flutter_launcher_icons/issues/54
  flutter_launcher_icons:
    git:
      url: git@github.com:fluttercommunity/flutter_launcher_icons.git
      ref: flavors

flutter:
  uses-material-design: true

  assets:
     - assets/

  # TODO(SF) BUILD watch https://github.com/flutter/flutter/issues/21682
  fonts:
    - family: Display Font
      fonts:
        - asset: assets/display_font.ttf
    # - family: No Continue
    #   fonts:
    #     - asset: assets/spirit/no_continue.ttf
    # - family: Pirata One
    #   fonts:
    #     - asset: assets/party_san/PirataOne-Regular.ttf
