const String shuttleEnHtml = '''
<body>
  <div class="section section-default">
    <div class="container">
      <div class="section-row">
        <div class="section-column maincontent-wrap">
          <div id="c604"
            class=" frame frame-default frame-type-table frame-layout-default frame-size-default frame-height-default frame-background-none frame-space-before-none frame-space-after-none frame-no-backgroundimage">
            <div class="frame-group-container">
              <div class="frame-group-inner">
                <div class="frame-container frame-container-default">
                  <div class="frame-inner">
                    <a id="c827"></a>
                    <div class="frame-header">
                      <h2 class="element-header  ">
                        <span>Mühlhausen trainstation -&gt; P.S:O:A</span>
                      </h2>
                    </div>
                    <div class="table-responsive">
                      <table class="table">
                        <tbody>
                          <tr>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              Wednesday
                            </td>
                            <td>
                              Thursday
                            </td>
                            <td>
                              Friday
                            </td>
                            <td>
                              Saturday
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              o'clock
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              11
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              13
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              17
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              19
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              21
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="section-column subcontent-wrap">
          <div id="c603"
            class=" frame frame-default frame-type-table frame-layout-default frame-size-default frame-height-default frame-background-none frame-space-before-none frame-space-after-none frame-no-backgroundimage">
            <div class="frame-group-container">
              <div class="frame-group-inner">
                <div class="frame-container frame-container-default">
                  <div class="frame-inner">
                    <a id="c828"></a>
                    <div class="frame-header">
                      <h2 class="element-header  ">
                        <span>P.S:O:A -&gt; Mühlhausen trainstation</span>
                      </h2>
                    </div>
                    <div class="table-responsive">
                      <table class="table">
                        <tbody>
                          <tr>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              Wednesday
                            </td>
                            <td>
                              Thursday
                            </td>
                            <td>
                              Friday
                            </td>
                            <td>
                              Saturday
                            </td>
                            <td>
                              Sunday
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              o'clock
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              1
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              30*
                            </td>
                            <td>
                              30*
                            </td>
                            <td>
                              30*
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              4
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              15
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              5
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              6
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              7
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              8
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              9
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              10
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              11
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              12
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              14
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              45
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              16
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              18
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                          <tr>
                            <td>
                              20
                            </td>
                            <td>
                              30
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                            <td>
                              &nbsp;
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="c701"
            class=" frame frame-default frame-type-text frame-layout-default frame-size-default frame-height-default frame-background-none frame-space-before-none frame-space-after-none frame-no-backgroundimage">
            <div class="frame-group-container">
              <div class="frame-group-inner">
                <div class="frame-container frame-container-default">
                  <div class="frame-inner">
                    <a id="c829"></a>
                    <p>* 15 min after the end of the mainstage show latest, not before 1:30 + access at flag-gate</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="c608"
            class=" frame frame-default frame-type-text frame-layout-default frame-size-default frame-height-default frame-background-none frame-space-before-none frame-space-after-none frame-no-backgroundimage">
            <div class="frame-group-container">
              <div class="frame-group-inner">
                <div class="frame-container frame-container-default">
                  <div class="frame-inner">
                    <a id="c830"></a>
                    <div class="frame-header">
                      <h2 class="element-header  ">
                        <span>PRICING</span>
                      </h2>
                    </div>
                    <p>Mühlhausen - P.S:O:A = 20,- € (1x to&amp;back)</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
''';
